#!/bin/sh

set -e -x

# Update and install git
apk --update add git make gcc libc-dev

# Install FPM
gem install fpm --no-doc --no-ri

# Get git tag
cd concourse-tag
TAG=$(git describe --tags | head -n 1)
cd ..

# Download Concourse and Fly
wget https://github.com/concourse/concourse/releases/download/${TAG}/concourse_linux_amd64
wget https://github.com/concourse/concourse/releases/download/${TAG}/fly_linux_amd64

# Set executable
chmod +x fly_linux_amd64 concourse_linux_amd64

# Package that goodness
fpm -s dir -t rpm -n concourse -v 4.0.0 fly_linux_amd64=/opt/concourse/fly concourse_linux_amd64=/opt/concourse/concourse
